import Head from 'next/head'
import Image from 'next/image'

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <header>
        <h1>WEBTECH WEBSITE</h1>
    </header>
      <main>
        <h2>CONTACTS</h2>
        <ul>
            <li>Come Chappuis</li>
            <li>Emma Varnier</li>
            <li>Thibaut d'Astorg</li>
            <li>Antoine Bertrand</li>
            <li>Charles Fabard</li>
        </ul>
        <ul>
            <li><a href="/">retour</a></li>
        </ul>
      </main>

      <footer>
        <a
          href="https://vercel.com?utm_source=create-next-app&utm_medium=default-template&utm_campaign=create-next-app"
          target="_blank"
          rel="noopener noreferrer"
        >
          Powered by{' '}
          <span>
            <Image src="/vercel.svg" alt="Vercel Logo" width={72} height={16} />
          </span>
        </a>
      </footer>
    </div>
  )
}
